---
- name: Install nginx
  become: yes
  yum:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm 
    state: present

- name: Install nginx package
  become: yes
  yum:
    name: nginx
    state: present
  when: not ansible_check_mode 

- name: start nginx
  become: yes
  command: service nginx start 

- name: Set auto start nginx
  become: yes
  command: chkconfig nginx on